name: publish-technical-documentation-release

permissions: {}

on:
  push:
    branches:
    - "release/v[0-9]+.[0-9]+"
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    paths:
    - "docs/sources/**"
  workflow_dispatch:
jobs:
  sync:
    if: github.repository == 'grafana/pyroscope'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-x64-small
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: grafana/writers-toolkit/publish-technical-documentation-release@53f56c6ad8d9870aff26be10a1db9d0f4652b63a
        with:
          release_tag_regexp: "^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
          release_branch_regexp: "^release/v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
          release_branch_with_patch_regexp: "^release/v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
          website_directory: content/docs/pyroscope
